#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

    default_indent = 2
    autocomplete_method = "coc"

    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

# SpaceVim layer config {{{
[[layers]]
  name = 'default'
# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = 'core'
  # file_tree_show_hidden = true

[[layers]]
  name = 'lang#c'
  clang_executable = "clang"
  enable_clang_syntax_highlight = true
  [layer.clang_std]
    cpp = 'c17'

[[layers]]
  name = 'lang#python'

[[layers]]
  name = 'lang#go'

[[layers]]
  name = 'leaderf'
[[layers]]
  name = 'format'
  format_on_save = true
[[layers]]
  name = 'git'
[[layers]]
  name = 'tools'
[[layers]]
  name = "lsp"
  filetypes = [
    "c",
    "cpp"
  ]
  [layers.override_cmd]
    c = ["ccls", "--log-file=/tmp/ccls.log"]
    cpp = ["ccls", "--log-file=/tmp/ccls.log"]

# }}} SpaceVim layer config

# Custom plugins {{{

[[custom_plugins]]
  name = 'matsub/rtcweb-sdp.vim'

[[custom_plugins]]
  name = 'https://github.com/kalcutter/vim-gn'

[[custom_plugins]]
  name = 'mtdl9/vim-log-highlighting'

[[custom_plugins]]
  name = 'aperezdc/vim-template'

[[custom_plugins]]
    name = 'skywind3000/vim-cppman'

# }}} Custom plugins
